// pages/blog/index.vue
<template>
  <div>
    <TitleBox>Blog</TitleBox>
    <div class="grid grid-cols-2 gap-2">
      <BlogPost v-for="post in posts" 
                :key="post" 
                :title="post.title" 
                :description="post.description" 
                :date="post.date" 
                :link="post._path" />
    </div>
  </div>
</template>

<script setup>
  const posts = await queryContent("/blog").only(["title", "description", "date", "_path"]).find()
</script>

// src/app/blog/page.jsx
import { getAllPosts } from "@/lib/posts.js";
import Link from "next/link"

export default function BlogPage() {
  return (
    <>
      <div className="grid grid-cols-2 gap-2">
        {getAllPosts().map(post => (
          <Link key={post.slug} href={`/blog/${post.slug}`}>
            <div className="flex flex-col justify-between gap-1 border-2 border-neutral-700 bg-neutral-800 rounded-xl p-4 hover:bg-neutral-700">
              <h4>{post.title}</h4>
              <p>{post.subtitle}</p>
              <p className="text-right">{post.date}</p>
            </div>
          </Link>
        ))}
      </div>
    </>
  )
};
